services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  backend:
    build: ./apps/backend
    ports:
      - "5000:5000"
    volumes:
      - ./apps/backend/src:/src
    depends_on:
      - mosquitto

  gateway:
    build: ./apps/gateway
    depends_on:
      - mosquitto

  tag:
    build: ./apps/tag
    depends_on:
      - mosquitto