services:
  # PostgreSQL database for backend persistence.
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=esl
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:        # Check when Postgres is up and running to then allow backend connection.
      test: ["CMD-SHELL", "pg_isready -U postgres -d esl"]
      interval: 2s
      timeout: 3s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MQTT broker used by backend, gateway, and tag simulator.
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  backend:
    build: ./apps/backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/esl
    volumes:
      - ./apps/backend/src:/src
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_healthy

  frontend:
    build: ./apps/frontend
    ports:
      - "4200:4200"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend

  gateway:
    build: ./apps/gateway
    depends_on:
      - mosquitto
    environment:
      - BROKER=mosquitto
      - PORT=1883
      - INPUT_TOPIC=tags/packets
      - CHECK_INTERVAL=2.0
      - LOW_BATTERY_THRESHOLD=20
      - OFFLINE_TIMEOUT_SECONDS=5.0
      - KNOWN_TAGS=1,2,3

  tag:
    build: ./apps/tag
    depends_on:
      - mosquitto
      
    environment:
      - BROKER=mosquitto
      - PORT=1883
      - TAG_ID=1
      - BATTERY=87
      - PRODUCT_ID=1001
      - RELIABILITY=0.9
      - PUBLISH_INTERVAL=2.0
      - PACKET_TOPIC=tags/packets

volumes:
  postgres_data:
