
# Fetch image
FROM python:3.12-slim

# Set working directory
WORKDIR /src

# Copy requirements first
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

