"""initial schema

Revision ID: b63d4d64d989
Revises: 
Create Date: 2026-04-21 23:33:24.429481
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b63d4d64d989'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payload_delivery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=127), nullable=False),
    sa.Column('final_price', sa.Integer(), nullable=False),
    sa.Column('delivery_state', sa.Enum('PENDING', 'DELIVERING', 'ACKNOWLEDGED', 'FAILED', name='deliverystate'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payload_delivery_tag_id'), 'payload_delivery', ['tag_id'], unique=False)
    op.create_table('tag_registry',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('ble_identifier', sa.String(length=64), nullable=True),
    sa.Column('connection_state', sa.Enum('UNKNOWN', 'DISCOVERED', 'CONNECTING', 'CONNECTED', 'DISCONNECTED', name='tagconnectionstate'), nullable=False),
    sa.Column('last_battery_percent', sa.Integer(), nullable=True),
    sa.Column('last_rssi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('ble_identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_registry')
    op.drop_index(op.f('ix_payload_delivery_tag_id'), table_name='payload_delivery')
    op.drop_table('payload_delivery')
    # ### end Alembic commands ###
